name: Backend CI/CD


on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main


env:
  DOCKER_IMAGE_NAME: srinivasbatthula05/coflow-backend


jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # Pull Code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Setup Node.js with cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      # Cache MongoDB binaries for mongodb-memory-server
      - name: Cache MongoDB binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/mongodb-binaries
          key: ${{ runner.os }}-mongodb-binaries

      # Install dependencies (cached)
      - name: Install dependencies
        working-directory: backend
        run: npm install
        
      # Run Tests (Jest + SuperTest)
      - name: Run Tests
        working-directory: backend
        env:
          Mongo_DB_URI: ${{ secrets.Mongo_DB_URI }}
          ALLOW_PROD_SEED: true
          BACKEND_ENV: test
        run: npm test

        # Set up Docker BuildX with cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('backend/package-lock.json', 'backend/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

        # Login's & Builds and Push's new Image to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract github-commit hash
      #   id: vars
      #   run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Build and Push Backend Image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/coflow-backend:${{ env.TAG }} ./backend
      #     docker push ${{ secrets.DOCKER_USERNAME }}/coflow-backend:${{ env.TAG }}
      
      # Build and Push Backend Docker image (using cache)
      - name: Build and Push Backend Image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            -t ${{ secrets.DOCKER_USERNAME }}/coflow-backend:latest \
            ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/coflow-backend:latest

      # Move cache to avoid overwriting on failure
      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

        # Updates `image-tag` in render to new one
      # - name: Update Render service with new image tag
      #   run: |
      #     curl -X PATCH "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}" \
      #       -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"dockerImage\":{\"image\":\"docker.io/${{ env.DOCKER_IMAGE_NAME }}\", \"tag\":\"${{ env.TAG }}\"}}"

        # Triggers Auto-ReDeploy on Render via deploy-hook
      - name: Trigger Backend Render Re-Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK_BACKEND }}
