name: Backend CI/CD


on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main


env:
  DOCKER_IMAGE_NAME: srinivasbatthula05/coflow-backend


jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # Pull Code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Setup Node.js with cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies (cached)
      - name: Install dependencies
        working-directory: backend
        run: npm install
        
      # Run Tests (Jest + SuperTest)
      - name: Run Tests
        working-directory: backend
        env:
          TEST_EMAIL: srinivasb.temp@gmail.com      # ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: 1234                       # ${{ secrets.TEST_PASSWORD }}
          SEED_MODE: fixtures
          BACKEND_ENV: test
        run: npm test

        # Set up Docker BuildX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Login's & Builds and Push's new Image to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and Push Backend Docker image (using cache)
      - name: Build and Push Backend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/coflow-backend:latest \
            ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/coflow-backend:latest

        # Triggers Auto-ReDeploy on Render via deploy-hook
      - name: Trigger Backend Render Re-Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK_BACKEND }}
